#!/usr/bin/env python3
"""
Directly generate blended images via chat image model.
Input: scene image + character image.
Output: final fused image generated by API.
"""

from __future__ import annotations

import argparse
import base64
import mimetypes
import re
from pathlib import Path
from typing import Any, Dict, List

import requests


DATA_URI_RE = re.compile(r"data:image/[^;]+;base64,([A-Za-z0-9+/=]+)")
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

DEFAULT_PROMPT = (
    "将第二张图中的角色合理且美观地融入第一张现实场景图中。"
    "允许对角色进行缩放与位置调整，并做适度光照/色温匹配，使其像真实拍摄的一部分。"
    "保持第一张图的构图与主体基本不变，不要新增无关元素。"
    "只输出一张最终融合后的图像。"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Direct blend via generative API")
    parser.add_argument("--test-dir", default=r"D:\sit_here\test_image")
    parser.add_argument("--model-image", default=r"D:\sit_here\l2d\model.png")
    parser.add_argument("--output-root", default=r"D:\sit_here\api_generated_images\direct_blend")
    parser.add_argument("--base-url", default="https://api.hiyo.top")
    parser.add_argument("--api-key", required=True)
    parser.add_argument("--model", default="gemini-3.1-flash-image")
    parser.add_argument("--prompt", default=DEFAULT_PROMPT)
    parser.add_argument("--timeout-sec", type=int, default=300)
    return parser.parse_args()


def file_to_data_uri(path: Path) -> str:
    mime = mimetypes.guess_type(path.name)[0] or "image/png"
    b64 = base64.b64encode(path.read_bytes()).decode("utf-8")
    return f"data:{mime};base64,{b64}"


def chat_completion(
    base_url: str,
    api_key: str,
    model: str,
    messages: List[Dict[str, Any]],
    timeout_sec: int,
) -> Dict[str, Any]:
    url = base_url.rstrip("/") + "/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload: Dict[str, Any] = {
        "model": model,
        "messages": messages,
        "modalities": ["text", "image"],
        "temperature": 0.2,
    }
    response = requests.post(url, headers=headers, json=payload, timeout=timeout_sec)
    response.raise_for_status()
    return response.json()


def extract_image_bytes(payload: Dict[str, Any]) -> bytes:
    msg = payload["choices"][0]["message"]
    content = msg.get("content")

    if isinstance(content, list):
        for part in content:
            if not isinstance(part, dict):
                continue
            if part.get("type") in {"output_image", "image"} and isinstance(part.get("b64_json"), str):
                return base64.b64decode(part["b64_json"])
            if part.get("type") == "image_url":
                image_url = part.get("image_url")
                if isinstance(image_url, dict):
                    src = image_url.get("url")
                else:
                    src = image_url
                if isinstance(src, str):
                    m = DATA_URI_RE.search(src)
                    if m:
                        return base64.b64decode(m.group(1))

    if isinstance(content, str):
        m = DATA_URI_RE.search(content)
        if m:
            return base64.b64decode(m.group(1))

    raise RuntimeError("No image found in API response")


def main() -> None:
    args = parse_args()
    test_dir = Path(args.test_dir)
    out_root = Path(args.output_root)
    out_root.mkdir(parents=True, exist_ok=True)

    model_path = Path(args.model_image)
    model_uri = file_to_data_uri(model_path)

    images = sorted(
        p for p in test_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    )
    if not images:
        raise SystemExit(f"No test images in: {test_dir}")

    for idx, scene_path in enumerate(images, start=1):
        scene_uri = file_to_data_uri(scene_path)
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": args.prompt},
                    {"type": "image_url", "image_url": {"url": scene_uri}},
                    {"type": "image_url", "image_url": {"url": model_uri}},
                ],
            }
        ]

        print(f"[{idx}/{len(images)}] generating {scene_path.name} ...")
        payload = chat_completion(
            base_url=args.base_url,
            api_key=args.api_key,
            model=args.model,
            messages=messages,
            timeout_sec=args.timeout_sec,
        )
        out_bytes = extract_image_bytes(payload)

        out_name = scene_path.stem + "_direct_blend.png"
        out_path = out_root / out_name
        out_path.write_bytes(out_bytes)
        print(f"  [ok] {out_path}")

    print("\nDone.")
    print(f"Output root: {out_root}")


if __name__ == "__main__":
    main()

